### ISSUE TITLE
Option to not use docker

### ISSUE THREAD

**Issue by pieterclaerhout** [jessarcher/zsh-artisan#14]
In our Laravel project, we have a `docker-compose.yml` file which is there just as a reference.

Since we aren't actually using Docker at this moment, the autocompletion returns errors as Docker isn't running.

What would be the best way to get around this?

Is there is an option to indicate that we don't want to use Docker or can the error be skipped if Docker isn't running?

**Comment by jessarcher** [comment]
Sorry about that! I hadn't considered this scenario.

An ENV var would probably be the easiest solution. I kinda rely on the error to remind me that I forgot to start my containers.

Feel free to open a PR otherwise I will try to get to this soon.
