### ISSUE TITLE
Sail?

### ISSUE THREAD

**Issue by devsquad-alvaro-meireles** [jessarcher/zsh-artisan#9]
Hello!

This plugin can work with Laravel Sail removing the necessity to use `sail` before each Artisan command?

**Comment by jessarcher** [comment]
Hey!

Check out this PR and branch https://github.com/jessarcher/zsh-artisan/pull/6 which I've been using for a while with Sail and other docker setups.

**Comment by devsquad-alvaro-meireles** [comment]
> Hey!
> 
> Check out [this PR and branch](https://github.com/jessarcher/zsh-artisan/pull/6) which I've been using for a while with Sail and other docker setups.

When it iwll be released?

**Comment by devsquad-alvaro-meireles** [comment]
> Hey!
> 
> Check out [this PR and branch](https://github.com/jessarcher/zsh-artisan/pull/6) which I've been using for a while with Sail and other docker setups.

Do you really use this with Laravel Sail? I'm try to use and I get this error: "artisan:11: command not found: artisan"
